PATH=.:$HOME/radiance/bin/:$PATH
RAYPATH=.:$HOME/radiance/lib/:$RAYPATH
MANPATH=:$HOME/radiance/man/:$MANPATH
export PATH RAYPATH MANPATH

chmod u+x radiance/bin/3ds2mgf
chmod u+x radiance/bin/bgraph
chmod u+x radiance/bin/bsdf2klems
chmod u+x radiance/bin/bsdf2ttree
chmod u+x radiance/bin/bsdfview
chmod u+x radiance/bin/cnt
chmod u+x radiance/bin/compamb
chmod u+x radiance/bin/cv
chmod u+x radiance/bin/dayfact
chmod u+x radiance/bin/dctimestep
chmod u+x radiance/bin/dgraph
chmod u+x radiance/bin/eplus_adduvf
chmod u+x radiance/bin/epw2wea
chmod u+x radiance/bin/ev
chmod u+x radiance/bin/evalglare
chmod u+x radiance/bin/falsecolor
chmod u+x radiance/bin/fieldcomb
chmod u+x radiance/bin/findglare
chmod u+x radiance/bin/gcomp
chmod u+x radiance/bin/genambpos
chmod u+x radiance/bin/genblinds
chmod u+x radiance/bin/genbox
chmod u+x radiance/bin/genBSDF
chmod u+x radiance/bin/genclock
chmod u+x radiance/bin/gendaylit
chmod u+x radiance/bin/gendaymtx
chmod u+x radiance/bin/genklemsamp
chmod u+x radiance/bin/genprism
chmod u+x radiance/bin/genrev
chmod u+x radiance/bin/genrhgrid
chmod u+x radiance/bin/gensky
chmod u+x radiance/bin/genskyvec
chmod u+x radiance/bin/gensurf
chmod u+x radiance/bin/genworm
chmod u+x radiance/bin/getbbox
chmod u+x radiance/bin/getinfo
chmod u+x radiance/bin/glare
chmod u+x radiance/bin/glarendx
chmod u+x radiance/bin/glaze
chmod u+x radiance/bin/glrad
chmod u+x radiance/bin/histo
chmod u+x radiance/bin/icalc
chmod u+x radiance/bin/ies2rad
chmod u+x radiance/bin/igraph
chmod u+x radiance/bin/lampcolor
chmod u+x radiance/bin/libmgf.a
chmod u+x radiance/bin/libqtrvu.a
chmod u+x radiance/bin/libradiance.a
chmod u+x radiance/bin/libraycalls.a
chmod u+x radiance/bin/librtrad.a
# chmod u+x radiance/bin/libtiff.so.5.2.0
chmod u+x radiance/bin/lookamb
chmod u+x radiance/bin/ltpict.pl
chmod u+x radiance/bin/ltview.pl
chmod u+x radiance/bin/macbethcal
chmod u+x radiance/bin/meta2bmp
chmod u+x radiance/bin/meta2tga
chmod u+x radiance/bin/mgf2inv
chmod u+x radiance/bin/mgf2meta
chmod u+x radiance/bin/mgf2rad
chmod u+x radiance/bin/mgfilt
chmod u+x radiance/bin/mkillum
chmod u+x radiance/bin/mkpmap
chmod u+x radiance/bin/mksource
chmod u+x radiance/bin/neaten
chmod u+x radiance/bin/nff2rad
chmod u+x radiance/bin/normpat
chmod u+x radiance/bin/normtiff
chmod u+x radiance/bin/obj2mesh
chmod u+x radiance/bin/obj2rad
chmod u+x radiance/bin/objline
chmod u+x radiance/bin/objpict
chmod u+x radiance/bin/objview
chmod u+x radiance/bin/oconv
chmod u+x radiance/bin/optics2rad
chmod u+x radiance/bin/pbilat
chmod u+x radiance/bin/pcomb
chmod u+x radiance/bin/pcompos
chmod u+x radiance/bin/pcond
chmod u+x radiance/bin/pcwarp
chmod u+x radiance/bin/pdfblur
chmod u+x radiance/bin/pexpand
chmod u+x radiance/bin/pextrem
chmod u+x radiance/bin/pfilt
chmod u+x radiance/bin/pflip
chmod u+x radiance/bin/pgblur
chmod u+x radiance/bin/phisto
chmod u+x radiance/bin/pinterp
chmod u+x radiance/bin/pkgBSDF
chmod u+x radiance/bin/plot4
chmod u+x radiance/bin/plotin
chmod u+x radiance/bin/plugins
chmod u+x radiance/bin/pmapdump
chmod u+x radiance/bin/pmblur
chmod u+x radiance/bin/pmdblur
chmod u+x radiance/bin/protate
chmod u+x radiance/bin/psign
chmod u+x radiance/bin/psmeta
chmod u+x radiance/bin/psort
chmod u+x radiance/bin/pvalue
chmod u+x radiance/bin/qt.conf
chmod u+x radiance/bin/ra_bmp
chmod u+x radiance/bin/rad
chmod u+x radiance/bin/rad2mgf
chmod u+x radiance/bin/raddepend
chmod u+x radiance/bin/ra_gif
chmod u+x radiance/bin/ra_hexbit
chmod u+x radiance/bin/ran2tiff
chmod u+x radiance/bin/ranimate
chmod u+x radiance/bin/ranimove
chmod u+x radiance/bin/ra_pfm
chmod u+x radiance/bin/ra_pict
chmod u+x radiance/bin/ra_ppm
chmod u+x radiance/bin/ra_ps
chmod u+x radiance/bin/ra_rgbe
chmod u+x radiance/bin/ra_t16
chmod u+x radiance/bin/ra_t8
chmod u+x radiance/bin/ra_tiff
chmod u+x radiance/bin/ra_xyze
chmod u+x radiance/bin/rcalc
chmod u+x radiance/bin/rcollate
chmod u+x radiance/bin/rcontrib
chmod u+x radiance/bin/replmarks
chmod u+x radiance/bin/rfluxmtx
chmod u+x radiance/bin/rhcopy
chmod u+x radiance/bin/rhinfo
chmod u+x radiance/bin/rholo
chmod u+x radiance/bin/rhoptimize
chmod u+x radiance/bin/rhpict
chmod u+x radiance/bin/rlam
chmod u+x radiance/bin/rlux
chmod u+x radiance/bin/rmtxop
chmod u+x radiance/bin/rpict
chmod u+x radiance/bin/rpiece
chmod u+x radiance/bin/rsensor
chmod u+x radiance/bin/rtrace
chmod u+x radiance/bin/rttree_reduce
chmod u+x radiance/bin/rvu
chmod u+x radiance/bin/tabfunc
chmod u+x radiance/bin/tmesh2rad
chmod u+x radiance/bin/total
chmod u+x radiance/bin/trad
chmod u+x radiance/bin/ttyimage
chmod u+x radiance/bin/vinfo
chmod u+x radiance/bin/vwrays
chmod u+x radiance/bin/vwright
chmod u+x radiance/bin/wrapBSDF
chmod u+x radiance/bin/x11.hdi
chmod u+x radiance/bin/x11meta
chmod u+x radiance/bin/xform
chmod u+x radiance/bin/xglaresrc
chmod u+x radiance/bin/ximage
chmod u+x radiance/bin/xshowtrace
chmod u+x radiance/bin/xyzimage
