PATH=.:$HOME/radiance/bin/:$PATH
RAYPATH=.:$HOME/radiance/lib/:$RAYPATH
MANPATH=:$HOME/radiance/man/:$MANPATH
export PATH RAYPATH MANPATH

chmod +x radiance/bin/3ds2mgf
chmod +x radiance/bin/bgraph
chmod +x radiance/bin/bsdf2klems
chmod +x radiance/bin/bsdf2ttree
chmod +x radiance/bin/bsdfview
chmod +x radiance/bin/cnt
chmod +x radiance/bin/compamb
chmod +x radiance/bin/cv
chmod +x radiance/bin/dayfact
chmod +x radiance/bin/dctimestep
chmod +x radiance/bin/dgraph
chmod +x radiance/bin/eplus_adduvf
chmod +x radiance/bin/epw2wea
chmod +x radiance/bin/ev
chmod +x radiance/bin/evalglare
chmod +x radiance/bin/falsecolor
chmod +x radiance/bin/fieldcomb
chmod +x radiance/bin/findglare
chmod +x radiance/bin/gcomp
chmod +x radiance/bin/genambpos
chmod +x radiance/bin/genblinds
chmod +x radiance/bin/genbox
chmod +x radiance/bin/genBSDF
chmod +x radiance/bin/genclock
chmod +x radiance/bin/gendaylit
chmod +x radiance/bin/gendaymtx
chmod +x radiance/bin/genklemsamp
chmod +x radiance/bin/genprism
chmod +x radiance/bin/genrev
chmod +x radiance/bin/genrhgrid
chmod +x radiance/bin/gensky
chmod +x radiance/bin/genskyvec
chmod +x radiance/bin/gensurf
chmod +x radiance/bin/genworm
chmod +x radiance/bin/getbbox
chmod +x radiance/bin/getinfo
chmod +x radiance/bin/glare
chmod +x radiance/bin/glarendx
chmod +x radiance/bin/glaze
chmod +x radiance/bin/glrad
chmod +x radiance/bin/histo
chmod +x radiance/bin/icalc
chmod +x radiance/bin/ies2rad
chmod +x radiance/bin/igraph
chmod +x radiance/bin/lampcolor
chmod +x radiance/bin/libmgf.a
chmod +x radiance/bin/libqtrvu.a
chmod +x radiance/bin/libradiance.a
chmod +x radiance/bin/libraycalls.a
chmod +x radiance/bin/librtrad.a
# chmod +x radiance/bin/libtiff.so.5.2.0
chmod +x radiance/bin/lookamb
chmod +x radiance/bin/ltpict.pl
chmod +x radiance/bin/ltview.pl
chmod +x radiance/bin/macbethcal
chmod +x radiance/bin/meta2bmp
chmod +x radiance/bin/meta2tga
chmod +x radiance/bin/mgf2inv
chmod +x radiance/bin/mgf2meta
chmod +x radiance/bin/mgf2rad
chmod +x radiance/bin/mgfilt
chmod +x radiance/bin/mkillum
chmod +x radiance/bin/mkpmap
chmod +x radiance/bin/mksource
chmod +x radiance/bin/neaten
chmod +x radiance/bin/nff2rad
chmod +x radiance/bin/normpat
chmod +x radiance/bin/normtiff
chmod +x radiance/bin/obj2mesh
chmod +x radiance/bin/obj2rad
chmod +x radiance/bin/objline
chmod +x radiance/bin/objpict
chmod +x radiance/bin/objview
chmod +x radiance/bin/oconv
chmod +x radiance/bin/optics2rad
chmod +x radiance/bin/pbilat
chmod +x radiance/bin/pcomb
chmod +x radiance/bin/pcompos
chmod +x radiance/bin/pcond
chmod +x radiance/bin/pcwarp
chmod +x radiance/bin/pdfblur
chmod +x radiance/bin/pexpand
chmod +x radiance/bin/pextrem
chmod +x radiance/bin/pfilt
chmod +x radiance/bin/pflip
chmod +x radiance/bin/pgblur
chmod +x radiance/bin/phisto
chmod +x radiance/bin/pinterp
chmod +x radiance/bin/pkgBSDF
chmod +x radiance/bin/plot4
chmod +x radiance/bin/plotin
chmod +x radiance/bin/plugins
chmod +x radiance/bin/pmapdump
chmod +x radiance/bin/pmblur
chmod +x radiance/bin/pmdblur
chmod +x radiance/bin/protate
chmod +x radiance/bin/psign
chmod +x radiance/bin/psmeta
chmod +x radiance/bin/psort
chmod +x radiance/bin/pvalue
chmod +x radiance/bin/qt.conf
chmod +x radiance/bin/ra_bmp
chmod +x radiance/bin/rad
chmod +x radiance/bin/rad2mgf
chmod +x radiance/bin/raddepend
chmod +x radiance/bin/ra_gif
chmod +x radiance/bin/ra_hexbit
chmod +x radiance/bin/ran2tiff
chmod +x radiance/bin/ranimate
chmod +x radiance/bin/ranimove
chmod +x radiance/bin/ra_pfm
chmod +x radiance/bin/ra_pict
chmod +x radiance/bin/ra_ppm
chmod +x radiance/bin/ra_ps
chmod +x radiance/bin/ra_rgbe
chmod +x radiance/bin/ra_t16
chmod +x radiance/bin/ra_t8
chmod +x radiance/bin/ra_tiff
chmod +x radiance/bin/ra_xyze
chmod +x radiance/bin/rcalc
chmod +x radiance/bin/rcollate
chmod +x radiance/bin/rcontrib
chmod +x radiance/bin/replmarks
chmod +x radiance/bin/rfl+xmtx
chmod +x radiance/bin/rhcopy
chmod +x radiance/bin/rhinfo
chmod +x radiance/bin/rholo
chmod +x radiance/bin/rhoptimize
chmod +x radiance/bin/rhpict
chmod +x radiance/bin/rlam
chmod +x radiance/bin/rl+x
chmod +x radiance/bin/rmtxop
chmod +x radiance/bin/rpict
chmod +x radiance/bin/rpiece
chmod +x radiance/bin/rsensor
chmod +x radiance/bin/rtrace
chmod +x radiance/bin/rttree_reduce
chmod +x radiance/bin/rvu
chmod +x radiance/bin/tabfunc
chmod +x radiance/bin/tmesh2rad
chmod +x radiance/bin/total
chmod +x radiance/bin/trad
chmod +x radiance/bin/ttyimage
chmod +x radiance/bin/vinfo
chmod +x radiance/bin/vwrays
chmod +x radiance/bin/vwright
chmod +x radiance/bin/wrapBSDF
chmod +x radiance/bin/x11.hdi
chmod +x radiance/bin/x11meta
chmod +x radiance/bin/xform
chmod +x radiance/bin/xglaresrc
chmod +x radiance/bin/ximage
chmod +x radiance/bin/xshowtrace
chmod +x radiance/bin/xyzimage
